Investments/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Investments.Models;

namespace Investments.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult StockInvestments()
        {
            return View();
        }

        public IActionResult NewHomeInvestment()
        {
            return View();
        }

        public IActionResult CalculateHouseInfomation(HouseInvestment houseInvestment)
        {
            // new
            ListOfHouse listOfHouses = new ListOfHouse();
            listOfHouses.CalculatePaymentAtDifferentIntrestRates(houseInvestment);

            // old 
            //houseInvestment.Principle = houseInvestment.PriceOfHouse;
            //houseInvestment.CalculateMortgagePayment();
            //houseInvestment.CalculateTotalCostAndPayedIntrest();

            return View(listOfHouses);
        }

        public IActionResult CalculateInvestments(Client client)
        {
            if (client.StockInvestment == null)
            {
                return RedirectToAction("Index", "Home");
            }

            client.StockInvestment.CalculateReturns();

            return View(client);
        }
    
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Investments/Controllers/TicTacToeController.cs
using System;
using Investments.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Investments.Controllers
{
    public class TicTacToeController : Controller
    {
        public static Game game = new Game();
        public static bool s = false;

        // GET: /<controller>/
        public IActionResult Index()
        {
            /*
             * Start Up Menu
             */
            return View();
        }

        public IActionResult DisplayGame(Game g)
        {

           if(s == false)
            {
                game.Player1 = g.Player1;
                game.Player2 = g.Player2;
                game.Player1.C = 'x';
                game.Player2.C = 'o';
                game.PlayerTurn = game.Player1;
                game.PlayerTurn.BoarderColor = game.Player1.BoarderColor;
            }

            /*
             * if players name not entered, 
             * redirect to main menu
             */
            if (game.Player1.Name == null || game.Player2.Name == null)
            {
                return RedirectToAction("Index");
            }

            s = true;
            return View(game);
        }

        public IActionResult PlayerMove(int row, int col, char c)
        {
            
            /*
             * if players name not entered, 
             * redirect to main menu
             */
            if (game.Player1.Name == null || game.Player2.Name == null)
            {
                return RedirectToAction("Index");
            }
            Console.WriteLine($"{game.CheckPlayer(c).Name} Made a Move");
            // mark player turn
            game.TicTacToeGame[row, col] = c;

            // check to see if player won
            if(game.CheckForVictory())
            {
                return RedirectToAction("Victory");
            }

            // check for a tie/draw
            if (game.Tie())
            {
                return RedirectToAction("Tie");
            }

            // next players move
            if (game.PlayerTurn.C.Equals(game.Player1.C))
            {
                game.PlayerTurn = game.Player2;
                game.PlayerTurn.BoarderColor = game.Player2.BoarderColor;
            } else
            {
                game.PlayerTurn = game.Player1;
                game.PlayerTurn.BoarderColor = game.Player1.BoarderColor;
            }

            return RedirectToAction("DisplayGame", game);
        }

        public IActionResult Tie()
        {
            /*
             * if players name not entered, 
             * redirect to main menu
             */
            if (game.Player1.Name == null || game.Player2.Name == null)
            {
                return RedirectToAction("Index");
            }

            game.ResetGame();
            return View(game);
        }

        public IActionResult Victory()
        {
            /*
             * if players name not entered, 
             * redirect to main menu
             */
            if (game.Player1.Name == null || game.Player2.Name == null)
            {
                return RedirectToAction("Index");
            }

            if(game.PlayerTurn.Name == game.Player1.Name)
            {
                game.PlayerTurn.CelebrationGifPath = "/Images/TicTacToe/Vanessa.gif";
            } else
            {
                game.PlayerTurn.CelebrationGifPath = "/Images/TicTacToe/Jose.gif";
            }

            game.ResetGame();
            return View(game);
        }
    }
}

Investments/Controllers/ToDoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Investments.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Investments.Controllers
{
    public class ToDoListController : Controller
    {
        public static ToDoList ToDoList = new ToDoList();
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(ToDoList);
        }

        /*
         * Add Item to ToDoList
         */
        public IActionResult AddItemView()
        {
            return View();
        }

        public IActionResult AddItem(ToDo toDo)
        {
            ToDoList.AddAssignment(toDo);

            return RedirectToAction("Index");
        }

        public IActionResult EditAssignmentView(int id)
        {
            ToDo toDo = new ToDo();
            toDo.ID = id;
            /*
             * find to do in list
             */
            int index = 0;
            foreach(ToDo assignment in ToDoList.ListOfAssignments)
            {
                if(id == assignment.ID)
                {
                    break;
                }
                index++;
            }

            toDo.Assignment= ToDoList.ListOfAssignments[index].Assignment;
            toDo.DateTime = ToDoList.ListOfAssignments[index].DateTime;

            return View(toDo);
        }

        public IActionResult EditAssignment(ToDo toDo)
        {
            /*
             * Find Index of Assignment
             */
            int index = 0;
            foreach(ToDo assignment in ToDoList.ListOfAssignments)
            {
                if(toDo.ID == assignment.ID)
                {
                    break;
                }
                index++;
            }
            ToDoList.ListOfAssignments[index].Assignment = toDo.Assignment;

            return RedirectToAction("Index");
        }

        public IActionResult DeleteAssignment(int id)
        {
            /*
             * Find Assignment to Delete
             */
            int index = 0;
            foreach(ToDo assignment in ToDoList.ListOfAssignments)
            {
                if(id == assignment.ID)
                {
                    break;
                }
                index++;
            }
            ToDo deleteToDo = ToDoList.ListOfAssignments[index];
            ToDoList.ListOfAssignments.Remove(deleteToDo);

            return RedirectToAction("Index");
        }
    }
}

Investments/Controllers/VanessaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Investments.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Investments.Controllers
{
    public class VanessaController : Controller
    {
        public IWebHostEnvironment webHostEnvironment { get; set; }

        public static List<DateIdea> DateIdeas = new List<DateIdea>();
        public static int IDForDateIdeas = 0;

        public VanessaController(IWebHostEnvironment e)
        {
            webHostEnvironment = e;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            // GET the Date Ideas From DataBase
            QueryDB queryDB = new QueryDB();
            DateIdeas = queryDB.GetDateIdeas();

            return View(DateIdeas);
        }

        public IActionResult Roulette()
        {
            Random rand = new Random();
            int randomNumber = rand.Next(0, DateIdeas.Count);
            int c = DateIdeas[randomNumber].ID;
            return RedirectToAction("DisplayDateIdeaView", new { id = c});
        }

        public IActionResult AddDateView()
        {
            return View();
        }

        public IActionResult DisplayDateIdeaView(int id)
        {
            DateIdea date = new DateIdea();

            foreach(DateIdea dateIdea in DateIdeas)
            {
                if(id == dateIdea.ID)
                {
                    date = dateIdea;
                    break;
                }
            }

            return View(date);
        }

        public IActionResult DeleteDateIdeaConfirmation(int id)
        {
            QueryDB queryDB = new QueryDB();
            DateIdea dateIdea = queryDB.GetDateIdea(id);
            return View(dateIdea);
        }

        public IActionResult DeleteDateIdeaFromDB(int id)
        {
            QueryDB queryDB = new QueryDB();
            DateIdea dateIdea = queryDB.GetDateIdea(id);
            queryDB.DeleteDateIdea(dateIdea);

            return RedirectToAction("Index");
        }

        public IActionResult AddDateIdea(DateIdea dateIdea)
        {
            dateIdea.ID = IDForDateIdeas;
            IDForDateIdeas++;

            /*
             *  put image in folder
             */
            FolderAndDirectories folderAndDirectories = new FolderAndDirectories(webHostEnvironment);
            dateIdea.ImagePath = folderAndDirectories.PutImageTo(dateIdea.ImageFile, "Images");

            DateIdeas.Add(dateIdea);

            // add to DataBase
            QueryDB queryDB = new QueryDB();
            queryDB.AddDateIdeaToDB(dateIdea);

            return RedirectToAction("Index");
        }

        public IActionResult EditDateIdeaView(int id)
        {
            QueryDB queryDB = new QueryDB();
            DateIdea dateIdea = queryDB.GetDateIdea(id);

            return View(dateIdea);
        }

        public IActionResult UpdateDateIdea(DateIdea dateIdea)
        {
            QueryDB queryDB = new QueryDB();
            queryDB.UpdateDateIdea(dateIdea);

            return RedirectToAction("Index");
        }
    }

}

Investments/Views/Home/CalculateHouseInfomation.cshtml
@model Investments.Models.ListOfHouse;
@{
    ViewData["Title"] = "House Information";
}

<!--
    create loop to view mortage payment at
    different intrest rates
-->

@foreach (HouseInvestment house in Model.LOH)
{
    <div class="card text-center">
        <div class="card-header">
            <code>
                Fixed Intrest Rate: @house.FixedIntrestRate%
            </code>
        </div>
        <div class="card-body">
            <h4 class="card-title display-4">
                Mortgage Payment: <code>
                    $@String.Format("{0:0,0.##}", house.MortgageMonthlyPayment)
                </code>
            </h4>
            <p class="card-text">
                The total money paid for this house was <code>$@String.Format("{0:0,0.##}", house.TotalCostPayed)</code> and
                the you paid <code>$@String.Format("{0:0,0.##}", house.PayedIntrest)</code> in intrest.
            </p>
        </div>
    </div>
    <br />
}

Investments/Views/Home/CalculateInvestments.cshtml
@model Investments.Models.Client;
@{
    ViewData["Title"] = "Returns";
}

<div class="container text-center">
    <h1 class="display-4">
        Calculated Returns
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bank" viewBox="0 0 16 16">
            <path d="M8 .95 14.61 4h.89a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v7a.5.5 0 0 1 .485.379l.5 2A.5.5 0 0 1 15.5 17H.5a.5.5 0 0 1-.485-.621l.5-2A.5.5 0 0 1 1 14V7H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 4h.89L8 .95zM3.776 4h8.447L8 2.05 3.776 4zM2 7v7h1V7H2zm2 0v7h2.5V7H4zm3.5 0v7h1V7h-1zm2 0v7H12V7H9.5zM13 7v7h1V7h-1zm2-1V5H1v1h14zm-.39 9H1.39l-.25 1h13.72l-.25-1z" />
        </svg>
    </h1>

    @{
        var month = 1;
        var year = 2021;
        var date = new DateTime(year, month, 27);
    }

    <!-- Table -->
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Money Contribution</th>
                <th scope="col">Months Profit</th>
                <th scope="col">Money</th>
            </tr>
        </thead>
        <tbody>

            @foreach (MonthlyIRData data in Model.StockInvestment.MonthlyIRDatas)
            {
                @if (month == 13)
                {
                    month = 1;
                    year++;
                }

                date = new DateTime(year, month, 27);
                month++;

                <tr>
                    <!-- DATE -->
                    <td>@date.ToString("F")</td>

                    <!-- MONEY CONTRIBUTION -->
                    <td>
                        <code>
                            @String.Format("{0:0,0.##}", data.MoneyContribution)
                        </code>
                    </td>

                    <!-- EACH MONTHS PROFITS -->
                    <td>
                        <code>
                            @String.Format("{0:0,0.##}", data.MonthlyProfit)
                        </code>
                    </td>

                    <!-- MONEY -->
                    <td>
                        <code>
                            @String.Format("{0:0,0.##}", data.Money)
                        </code>
                    </td>

             
                </tr>         

            }

        </tbody>
    </table>

    <div>
        <p class="lead">
            Net Profit:
            <code>
                $@String.Format("{0:0,0.##}", @Model.StockInvestment.NetProfit)
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bar-chart-fill" viewBox="0 0 16 16">
                    <path d="M1 11a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3zm5-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2z" />
                </svg>
            </code>
        </p>
    </div>
</div>

Investments/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <!-- Stock/Home Investment Buttons -->
    <div class="row justify-content-center">

        <!-- Stock Investments -->
        <!--<div class="col-2">

            <form asp-controller="Home" asp-action="StockInvestments">

                <input type="submit" class="btn btn-success" value="Sock Investments" />

            </form>

        </div>-->

        <!-- Home Investments -->
        <!--<div class="col-2">

            <form asp-controller="Home" asp-action="NewHomeInvestment">

                <input type="submit" class="btn btn-primary" value="Home Investments" />

            </form>

        </div>-->

        <!-- To Do List -->
        <div class="col-6">
            <form asp-controller="ToDoList" asp-action="Index">

                <input type="submit" class="btn btn-warning" value="To Do List Jose" />

            </form>
        </div>

        <!-- TIC TAC TOE GAME -->
        <div class="col-6">
            <form asp-controller="TicTacToe" asp-action="Index">

                <input type="submit" class="btn btn-primary" value="TicTacToe Game" />

            </form>
        </div>

        <!-- Date Ideas -->
        <!--<div class="col-2">
            <form asp-controller="Vanessa" asp-action="Index">

                <input type="submit" class="btn btn-success" value="Date Ideas With Vanessa: NOT WORKING DON'T CLICK" />

            </form>
        </div>-->

    </div>

    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>


</div>

Investments/Views/Home/NewHomeInvestment.cshtml
@model Investments.Models.HouseInvestment;
@{
    ViewData["Title"] = "New Home Investment";
}



<div class="text-center">

    <h1 class="display-4">New Home Investment</h1>

</div>

<!--
       Form for Home Investment
-->
<div>

    <form asp-controller="Home" asp-action="CalculateHouseInfomation">

        <!-- Price of House -->
        <label class="lead">Price of House:
            <code>Don't include $ or ,</code> </label>
        <input class="form-control" placeholder="$500,000"
               type="number" asp-for="PriceOfHouse" />

        <!-- Down Payment -->
        <label class="lead">Down Payment:
            <code>Don't include $ or ,</code> </label>
        <input class="form-control" placeholder="$30,000"
               type="number" asp-for="DownPayment" />

        <!-- Duration of Loan -->
        <label>Duration of Loan: (In Years)</label>
        <input class="form-control" placeholder="30"
               type="number" asp-for="DurationOfLoanInYears" />

        <!-- Fixed Intrest Rate -->
        <label>Fixed Intrest Rate:</label>
        <input class="form-control" placeholder="5"
               type="number" asp-for="FixedIntrestRate"/>

        <!-- Credit Score -->
        <label class="lead">Credit Score:</label>
        <input class="form-control" placeholder="720"
               type="number" asp-for="CreditScore" />

        <br />
        <input class="btn btn-primary"
               type="submit" 
               value="Calculate Monthly Mortgage Payment" />

    </form>

</div>

Investments/Views/Home/StockInvestments.cshtml
@model Investments.Models.Client;
@{
    ViewData["Title"] = "Sock Investments";
}

<div class="container center-text">

    <h1 class="display-4">Stock Investments</h1>

    <form asp-controller="Home" asp-action="CalculateInvestments">

        <!-- Starting Balance Invested-->
        <code>Starting Balance Invested:</code>
        <input type="number" class="form-control" placeholder="7000"
               asp-for="StockInvestment.MoneyInvested"/>

        <!-- How Many Months -->
        <code>Number of Months to Invest:</code>
        <input type="number" class="form-control" placeholder="60"
               asp-for="StockInvestment.NumMonths"/>

        <!-- Monthly Contribution -->
        <code>Monthly Contribution:</code>
        <input type="number" class="form-control" placeholder="100"
               asp-for="StockInvestment.MonthlyContribution"/>

        <br /><br />
        <!-- Run the Code -->
        <input type="submit" value="See Returns" class="btn btn-primary"/>

    </form>

</div>